# Generated by Django 4.1.7 on 2023-03-14 09:50
import os

from django.db import migrations, connection


class Migration(migrations.Migration):

    def load_states_from_sql(apps, schema_editor):
        file_path = os.path.join(os.path.dirname(__file__), 'states.sql')
        for sql_statement in open(file_path).readlines():
            with connection.cursor() as cursor:
                cursor.execute(sql_statement)

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_states_from_sql),
    ]
